export const core = {
  background: '#0F1115',
  'on-background': '#F5F7FA',
} as const

export const rgb = {
  white: '255, 255, 255',
  black: '0, 0, 0',
  'accent-mint': '184, 243, 107',
  'accent-purple': '167, 139, 250',
  'accent-orange': '255, 184, 107',
  'accent-cyan': '125, 211, 252',
  'accent-pink': '249, 168, 212',
  'persona-green': '184, 243, 107',
  'persona-blue': '125, 211, 252',
  'persona-pink': '249, 168, 212',
  'persona-orange': '251, 146, 60',
  'tab-purple': '167, 139, 250',
  'badge-amber': '255, 189, 46',
  'orange-deep': '249, 115, 22',
} as const

export const canvas = {
  DEFAULT: '#0F1115',
  surface: '#11150C',
  secondary: '#171A20',
  elevated: '#1E222B',
  dim: '#111317',
  bright: '#37393e',
} as const

export const container = {
  lowest: '#0c0e12',
  low: '#1a1c20',
  DEFAULT: '#1e2024',
  high: '#282a2e',
  highest: '#333539',
} as const

export const border = {
  subtle: 'rgba(255, 255, 255, 0.06)',
} as const

export const accent = {
  mint: '#B8F36B',
  purple: '#A78BFA',
  orange: '#FFB86B',
  cyan: '#7DD3FC',
  pink: '#F9A8D4',
} as const

export const text = {
  primary: '#F5F7FA',
  secondary: '#9CA3AF',
  muted: '#6B7280',
  'on-surface': '#e2e2e8',
  'on-surface-variant': '#c2c9b3',
} as const

export const material = {
  primary: '#fdfff2',
  'on-primary': '#203700',
  'primary-container': '#b8f36b',
  'on-primary-container': '#456f00',
  'primary-fixed': '#b9f46c',
  'primary-fixed-dim': '#9ed753',
  'on-primary-fixed': '#102000',
  'on-primary-fixed-variant': '#304f00',
  'inverse-primary': '#416900',
  secondary: '#cebdff',
  'on-secondary': '#381385',
  'secondary-container': '#4f319c',
  'on-secondary-container': '#bea8ff',
  'secondary-fixed': '#e8ddff',
  'secondary-fixed-dim': '#cebdff',
  'on-secondary-fixed': '#21005e',
  'on-secondary-fixed-variant': '#4f319c',
  tertiary: '#fdfdff',
  'on-tertiary': '#003547',
  'tertiary-container': '#bce7ff',
  'on-tertiary-container': '#006c8d',
  'tertiary-fixed': '#c0e8ff',
  'tertiary-fixed-dim': '#7bd1fa',
  'on-tertiary-fixed': '#001e2b',
  'on-tertiary-fixed-variant': '#004d66',
  error: '#ffb4ab',
  'on-error': '#690005',
  'error-container': '#93000a',
  'on-error-container': '#ffdad6',
  outline: '#8d937f',
  'outline-variant': '#434938',
  'surface-variant': '#333539',
  'surface-tint': '#9ed753',
  'inverse-surface': '#e2e2e8',
  'inverse-on-surface': '#2f3035',
  'surface-bright': '#37393e',
  'surface-dim': '#111317',
} as const

export const palette = {
  'bg-main': canvas.DEFAULT,
  'page-bg': canvas.DEFAULT,
  background: canvas.DEFAULT,
  surface: canvas.surface,
  'surface-secondary': canvas.secondary,
  'surface-elevated': canvas.elevated,
  'surface-dim': canvas.dim,
  'surface-bright': canvas.bright,
  'container-lowest': container.lowest,
  'container-low': container.low,
  container: container.DEFAULT,
  'container-high': container.high,
  'container-highest': container.highest,
  'border-subtle': border.subtle,
  'accent-mint': accent.mint,
  'accent-purple': accent.purple,
  'accent-cyan': accent.cyan,
  'accent-orange': accent.orange,
  'accent-pink': accent.pink,
  'text-primary': text.primary,
  'text-secondary': text.secondary,
  'text-muted': text.muted,
  'text-on-accent': '#11150C',
  'on-background': core['on-background'],
  'persona-green': accent.mint,
  'persona-blue': accent.cyan,
  'persona-pink': accent.pink,
  'persona-orange': '#FB923C',
  'tab-purple': accent.purple,
  'badge-amber': '#FFBD2E',
  'orange-deep': '#F97316',
  white: '#FFFFFF',
  black: '#000000',
  primary: material.primary,
  'on-primary': material['on-primary'],
  'primary-container': material['primary-container'],
  'on-primary-container': material['on-primary-container'],
  'primary-fixed': material['primary-fixed'],
  'primary-fixed-dim': material['primary-fixed-dim'],
  'on-primary-fixed': material['on-primary-fixed'],
  'on-primary-fixed-variant': material['on-primary-fixed-variant'],
  'inverse-primary': material['inverse-primary'],
  secondary: material.secondary,
  'on-secondary': material['on-secondary'],
  'secondary-container': material['secondary-container'],
  'on-secondary-container': material['on-secondary-container'],
  'secondary-fixed': material['secondary-fixed'],
  'secondary-fixed-dim': material['secondary-fixed-dim'],
  'on-secondary-fixed': material['on-secondary-fixed'],
  'on-secondary-fixed-variant': material['on-secondary-fixed-variant'],
  tertiary: material.tertiary,
  'on-tertiary': material['on-tertiary'],
  'tertiary-container': material['tertiary-container'],
  'on-tertiary-container': material['on-tertiary-container'],
  'tertiary-fixed': material['tertiary-fixed'],
  'tertiary-fixed-dim': material['tertiary-fixed-dim'],
  'on-tertiary-fixed': material['on-tertiary-fixed'],
  'on-tertiary-fixed-variant': material['on-tertiary-fixed-variant'],
  error: material.error,
  'on-error': material['on-error'],
  'error-container': material['error-container'],
  'on-error-container': material['on-error-container'],
  outline: material.outline,
  'outline-variant': material['outline-variant'],
  'surface-variant': material['surface-variant'],
  'surface-tint': material['surface-tint'],
  'inverse-surface': material['inverse-surface'],
  'inverse-on-surface': material['inverse-on-surface'],
} as const

export const personaColorMap: Record<string, string> = {
  green: palette['persona-green'],
  blue: palette['persona-blue'],
  pink: palette['persona-pink'],
  purple: palette['tab-purple'],
  orange: palette['persona-orange'],
} as const

export const accentColorMap: Record<string, string> = {
  mint: accent.mint,
  purple: accent.purple,
  cyan: accent.cyan,
  orange: accent.orange,
  pink: accent.pink,
} as const

export const accentRgbMap: Record<string, string> = {
  mint: rgb['accent-mint'],
  purple: rgb['accent-purple'],
  cyan: rgb['accent-cyan'],
  orange: rgb['accent-orange'],
  pink: rgb['accent-pink'],
} as const

export const cssVars: Record<string, string> = {
  '--accent-mint': accent.mint,
  '--accent-purple': accent.purple,
  '--accent-cyan': accent.cyan,
  '--accent-orange': accent.orange,
  '--accent-pink': accent.pink,
  '--rgb-accent-mint': rgb['accent-mint'],
  '--rgb-accent-purple': rgb['accent-purple'],
  '--rgb-accent-cyan': rgb['accent-cyan'],
  '--rgb-accent-orange': rgb['accent-orange'],
  '--rgb-accent-pink': rgb['accent-pink'],
  '--rgb-white': rgb.white,
  '--rgb-black': rgb.black,
  '--rgb-orange-deep': rgb['orange-deep'],
  '--rgb-badge-amber': rgb['badge-amber'],
  '--rgb-tab-purple': rgb['tab-purple'],
  '--rgb-persona-green': rgb['persona-green'],
  '--rgb-persona-blue': rgb['persona-blue'],
  '--rgb-persona-pink': rgb['persona-pink'],
  '--rgb-persona-orange': rgb['persona-orange'],
  '--color-page-bg': canvas.DEFAULT,
  '--color-surface': canvas.surface,
  '--color-surface-secondary': canvas.secondary,
  '--color-surface-elevated': canvas.elevated,
  '--color-border-subtle': border.subtle,
  '--color-text-primary': text.primary,
  '--color-text-secondary': text.secondary,
  '--color-text-muted': text.muted,
  '--color-text-on-accent': '#11150C',
  '--color-persona-green': accent.mint,
  '--color-persona-blue': accent.cyan,
  '--color-persona-pink': accent.pink,
  '--color-persona-orange': '#FB923C',
  '--color-tab-purple': accent.purple,
  '--color-badge-amber': '#FFBD2E',
  '--color-orange-deep': '#F97316',
  '--color-white': '#FFFFFF',
  '--color-black': '#000000',
  '--color-metallic-start': '#121214',
  '--color-metallic-mid': '#0F0F11',
  '--color-metallic-end': '#0C0C0E',
  '--color-metallic-start-hover': '#17171A',
  '--color-metallic-mid-hover': '#111114',
} as const

export type PaletteKey = keyof typeof palette
